---
layout: post
title: "Quantifying Disturbance Events: Disturbance Overview"
date:  2015-11-23
authors: [Leah A. Wasser, Megan A. Jones]
dateCreated:  2015-11-23
lastModified: `r format(Sys.time(), "%Y-%m-%d")`
categories: [Coding and Informatics]
category: coding-and-informatics
tags: [R, time-series]
mainTag:
scienceThemes: [phenology, disturbance]
description: "This page provides materials on ecological disturbances, the 2013 
Colorado floods, disturbance return intervals, and the basics of LiDAR.  This 
material will prepare students to learn about and discuss how data can be used 
to increase our understanding of the causes and effects of a disturbance event."
code1:
image:
  feature: TeachingModules.jpg
  credit: A National Ecological Observatory Network (NEON) - Teaching Module
  creditlink: http://www.neoninc.org
permalink: /R/Boulder-Flood-PreClassroom/
code1: 
comments: false
---

{% include _toc.html %}

#Introduction to Disturbance Events

Within ecology, disturbance events are those events which cause dramatic change
in an ecosystem through a temporary, often rapid, change in environmental
conditions. Although the disturbance events themselves can be of short duration,
the ecological effects last decades, if not longer. 

Common examples of natural ecological disturbances include hurricanes, fires, 
floods, earthquakes and windstorms. 


IMAGE LIKE: http://cquest.arc.nasa.gov:8399/casa/global/images/slide1a.gif
Common natural ecological disturbances -- Image from NASA-CASA Project


Disturbance events can also be human caused: clear cuts when logging, fires to clear forests for cattle grazing or the building of new housing developments are all common disturbances. 


IMAGE LIKE:  url="http://cquest.arc.nasa.gov:8399/casa/global/images/slide2a.gif 
Common human-caused ecological disturbances -- Image from NASA-CASA Project


Ecological communities are often more resilient to some types of disturbance than
others. Some communities are even dependent on cyclical disturbance events. 
Lodgepole pine (_Pinus_ _contorta_) forests in the Western US are dependent on
frequent stand-replacing fires to release seeds and spur the growth of young 
trees.  

IMAGE LIKE: http://sustain.sfsu.edu/sustain/sustain/files/assets/images/Pinus%20Contorta%20forest%2C%20post%20fire.jpg
Regrowth of Lodgepole Pine *Pinus* *contorta* after a stand-replacing fire -- Image: Creative Commons Attribution

However, in discussions of ecological disturbance events we think about events 
that disrupt the status of the ecosystem and change the structure of the
landscape.  