---
layout: post
title: "Title Here"
date:   2016-01-08
authors: [ ]
contributors: [ ] 
dateCreated: 2016-01-08
lastModified: `r format(Sys.time(), "%Y-%m-%d")`
packagesLibraries: [ ]
tags: [phenology]
mainTag: 
category: [self-paced-tutorial]
description: "Brief description in plain text."
code1: use-if-associated-code.R
image:
  feature: lidar_GrandMesa.png
  credit: LiDAR data collected over Grand Mesa, Colorado - National Ecological Observatory Network (NEON)
  creditlink: http://www.neoninc.org
permalink: 
comments: false
---

{% include _toc.html %}

**R Skill Level:** Intermediate - you've got the basics of `R` down.

<div id="objectives" markdown="1">

###Goals / Objectives
After completing this activity, you will:

 * 

##Things You’ll Need To Complete This Lesson
To complete this lesson: you will need the most current version of R, and 
preferably RStudio, loaded on your computer.

###Install R Packages
* **ggplot2:** `install.packages("ggplot2")`


[More on Packages in R - Adapted from Software Carpentry.]({{site.baseurl}}R/Packages-In-R/)

###Download Data 
(include file that inserts a button to download data from Figshare & text about data.  Feel free to just add text until the data set is finalized and uploaded).

{% include/dataSubsets/_data_Met-Time-Series.html %}  


****
(include file that inserts a links on setting the working directory and on accessing the R code for any challenge activities).
{% include/_greyBox-wd-rscript.html %}

**Tabular Time Series Lesson Series:** This lesson is part of a lesson series on 
[tabular time series data in R ]({{ site.baseurl }}self-paced-tutorials/tabular-time-series).   

(If you choose to have >1 lesson)


****

##Skills Needed
This lessons assumes familiarity with both the `dplyr` package and `ggplot()` in
the `ggplot2` package.  (Delete section if not needed).

##Additional Resources

* (links if you want to provide)

</div>

